//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HicsBL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class itin18_aktEntities : DbContext
    {
        public itin18_aktEntities()
            : base("name=itin18_aktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("itin18_aktEntities", "fn_show_users")]
        public virtual IQueryable<fn_show_users_Result> fn_show_users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_show_users_Result>("[itin18_aktEntities].[fn_show_users]()");
        }
    
        public virtual int sp_add_user(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_user", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_add_usergroup(string name, Nullable<int> userlifetime)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var userlifetimeParameter = userlifetime.HasValue ?
                new ObjectParameter("userlifetime", userlifetime) :
                new ObjectParameter("userlifetime", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_usergroup", nameParameter, userlifetimeParameter);
        }
    
        public virtual int sp_change_password(string name, string oldpassword, string newpassword)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var oldpasswordParameter = oldpassword != null ?
                new ObjectParameter("oldpassword", oldpassword) :
                new ObjectParameter("oldpassword", typeof(string));
    
            var newpasswordParameter = newpassword != null ?
                new ObjectParameter("newpassword", newpassword) :
                new ObjectParameter("newpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_change_password", nameParameter, oldpasswordParameter, newpasswordParameter);
        }
    
        public virtual int sp_insert_test_data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_test_data");
        }
    }
}
